FROM oven/bun:1.2-alpine AS build

WORKDIR /app

COPY src/backend/package.json ./package.json
RUN bun install --frozen-lockfile

COPY src/backend .
RUN bun run build

FROM oven/bun:1.2-alpine AS runtime

WORKDIR /app

COPY src/backend/package.json ./package.json
RUN bun install --frozen-lockfile --production

COPY --from=build /app/dist ./dist
COPY etc ./etc

EXPOSE 3000

CMD ["bun", "run", "dist/main.js"]
